#!/usr/bin/env python3
"""BTC-CORE: wire the `aspaper` fork into the generated Gradle build files.

This is all that is left of the old injection pipeline. Every BTC modification to Java source now
lives in Paperweight feature patches, applied by `git am`:

    aspaper-server/minecraft-patches/features/0003-BTC-CORE-hooks.patch   decompiled overlay
    aspaper-server/paper-patches/features/0007-BTC-CORE-hooks.patch       paper-server
    aspaper-api/paper-patches/features/0002-BTC-CORE-hooks.patch          paper-api

The three edits below cannot follow them there. `aspaper-api/build.gradle.kts` and
`aspaper-server/build.gradle.kts` are generated by Paperweight and gitignored, and both patch dirs
carry `build.gradle.kts` in their `excludes`, so they belong to no patch tree at all. They also have
to be in place *before* the fork-aware tasks exist: without `forks.register("aspaper")` Gradle fails
with "Task 'applyAllServerPatches' not found", which is why CI runs this once before applying
server patches.

Idempotent: each edit is skipped when its result is already present. Exits non-zero if an anchor no
longer matches, because a missed edit here breaks the build in a way that reads like a Gradle bug.
"""

import os
import sys

FAILURES = []


def rewrite(path, anchor, replacement, done_marker, label):
    """Replace `anchor` with `replacement` in `path`, unless `done_marker` says it already happened.

    A missing file is not an error: Paperweight generates these, so an early run legitimately finds
    nothing. A file that exists but no longer contains the anchor *is* an error — that is upstream
    having moved the ground under us.
    """
    if not os.path.exists(path):
        return False
    with open(path, encoding="utf-8") as fh:
        content = fh.read()
    if done_marker in content:
        return False
    if anchor not in content:
        FAILURES.append((path, label, anchor.splitlines()[0][:80]))
        print(f"  [WARN] anchor not found in {path}: {label}")
        return False
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(content.replace(anchor, replacement, 1))
    print(f"  [OK] {label}")
    return True


PAPERWEIGHT_ANCHOR = """    updatingMinecraft {
        // oldPaperCommit = "d4fe85375af18bfa88f44d7c1e6a61904ae550cc"
    }"""

PAPERWEIGHT_FORK = """    val aspaper = forks.register("aspaper") {
        upstream.patchDir("paperServer") {
            upstreamPath = "paper-server"
            excludes = setOf("src/minecraft", "patches", "build.gradle.kts")
            patchesDir = rootDirectory.dir("aspaper-server/paper-patches")
            outputDir = rootDirectory.dir("paper-server")
        }
    }

    activeFork = aspaper

//    updatingMinecraft {
//        oldPaperCommit = "d4fe85375af18bfa88f44d7c1e6a61904ae550cc"
//    }"""


def main():
    print("=== BTC-CORE: registering the aspaper fork ===")

    rewrite(
        "aspaper-api/build.gradle.kts",
        "dependencies {\n    // api dependencies are listed transitively to API consumers",
        'dependencies {\n    api(project(":api")) //ASP\n    // api dependencies are listed transitively to API consumers',
        'api(project(":api"))',
        "aspaper-api: ASP API dependency",
    )

    rewrite(
        "aspaper-server/build.gradle.kts",
        'implementation(project(":paper-api"))',
        'implementation(project(":aspaper-api")) //ASP\n    implementation(project(":core")) //ASP',
        'implementation(project(":aspaper-api"))',
        "aspaper-server: swap paper-api for aspaper-api, add core",
    )

    rewrite(
        "aspaper-server/build.gradle.kts",
        PAPERWEIGHT_ANCHOR,
        PAPERWEIGHT_FORK,
        "val aspaper = forks.register",
        "aspaper-server: paperweight fork registration",
    )

    if FAILURES:
        print("\n=== FAILED ===")
        for path, label, anchor in FAILURES:
            print(f"  {path}: {label}\n    {anchor}")
        sys.exit(1)

    print("=== BTC-CORE: fork registered ===")


if __name__ == "__main__":
    main()
